#!/usr/bin/env python
import sys, os

components = ['gtest', '..']
recurse    = lambda ctx : map(lambda proj: ctx.recurse(proj), components)

def options(opt):
    opt.load('g++')
    recurse(opt)

def configure(cfg):
    cfg.load('g++')
    recurse(cfg)

def build(bld):
    recurse(bld)

    bld(
        target          = 'main',
        features        = 'cxx cxxprogram',
        source          = bld.path.ant_glob('*.cc'),
        use             = ['ranger', 'gtest'],
        install_path    = 'bin',
        cxxflags        = [
                '-g',
                '-O1',
                '-Wall',
                '-Wextra',
                '-pedantic',
                #'-DRANGER_DISABLE',
            ],
        includes       = '.',
    )
